name: senbet_school
description: Sunday School – Textbook Library
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  syncfusion_flutter_pdfviewer: ^33.2.13
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/library.json
    - assets/books/
    - assets/subjects/
    - assets/grade_1/
    - assets/grade_2/
    - assets/grade_3/
    - assets/grade_4/
    - assets/grade_5/
    - assets/grade_6/
    - assets/grade_7/
    - assets/grade_8/
    - assets/grade_9/
    - assets/grade_10/
    - assets/grade_11/
    - assets/grade_12/
